{% set name = "mcp" %}
{% set version = "1.24.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mcp-{{ version }}.tar.gz
  sha256: aeaad134664ce56f2721d1abf300666a1e8348563f4d3baff361c3b652448efc

build:
  entry_points:
    - mcp = mcp.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - anyio >=4.5
    - httpx >=0.27.1
    - httpx-sse >=0.4
    - jsonschema >=4.20.0
    - pydantic >=2.11.0,<3.0.0
    - pydantic-settings >=2.5.2
    - pyjwt >=2.10.1
    - python-dotenv >=1.0.0
    - python-multipart >=0.0.9
    - pywin32-on-windows
    - rich >=13.9.4
    - sse-starlette >=1.6.1
    - starlette >=0.27
    - typer >=0.16.0
    - typing-extensions >=4.9.0
    - typing-inspection >=0.4.1
    - uvicorn >=0.31.1
  run_constrained:
    - pywin32 >=310

test:
  imports:
    - mcp
    - mcp.os.win32.utilities
  commands:
    - pip check
    - mcp --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Model Context Protocol SDK
  home: https://github.com/modelcontextprotocol/python-sdk
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dbast
