{% set name = "mcp" %}
{% set version = "1.9.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mcp-{{ version }}.tar.gz
  sha256: 19879cd6dde3d763297617242888c2f695a95dfa854386a6a68676a646ce75e4

build:
  entry_points:
    - mcp = mcp.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - anyio >=4.5
    - httpx >=0.27
    - httpx-sse >=0.4
    - pydantic >=2.7.2,<3.0.0
    - pydantic-settings >=2.5.2
    - python-dotenv >=1.0.0
    - python-multipart >=0.0.9
    - rich >=13.9.4
    - sse-starlette >=1.6.1
    - starlette >=0.27
    - typer >=0.12.4
    - uvicorn >=0.23.1
  run_constrained:
    # Remove once typer is compatible with click >=8.2.0
    # see https://github.com/modelcontextprotocol/python-sdk/issues/688
    - click <8.2.0

test:
  imports:
    - mcp
  commands:
    - pip check
    - mcp --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Model Context Protocol SDK
  home: https://github.com/modelcontextprotocol/python-sdk
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dbast
