{% set name = "mcp" %}
{% set version = "1.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mcp-{{ version }}.tar.gz
  sha256: 3c7651c053d635fd235990a12e84509fe32780cd359a5bbef352e20d4d963c05

build:
  skip: true  # [py<310]
  # entry_points:
  #   - mcp = mcp.cli:app
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - anyio >=4.5
    - httpx >=0.27
    - httpx-sse >=0.4
    - pydantic >=2.7.2,<3.0.0
    - pydantic-settings >=2.5.2
    # - python-dotenv >=1.0.0
    - python-multipart >=0.0.9
    - rich >=13.9.4
    - sse-starlette >=1.6.1
    - starlette >=0.27
    # - typer >=0.12.4
    - uvicorn >=0.23.1

test:
  imports:
    - mcp
  commands:
    - pip check
    # - mcp --help
  requires:
    - pip
    - python

about:
  home: https://modelcontextprotocol.io/
  summary: The official Python SDK for Model Context Protocol servers and clients
  description: |
    The Model Context Protocol allows applications to provide context for LLMs in a standardized way, separating the concerns of providing context from the actual LLM interaction. This Python SDK implements the full MCP specification, making it easy to:

    * Build MCP clients that can connect to any MCP server
    * Create MCP servers that expose resources, prompts and tools
    * Use standard transports like stdio and SSE
    * Handle all MCP protocol messages and lifecycle events
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/modelcontextprotocol/python-sdk
  doc_url: https://github.com/modelcontextprotocol/python-sdk/blob/main/README.md

extra:
  recipe-maintainers:
    - dbast
